# Environment Variables - For Production Server Distribution

# Client Network Setting (hostname)
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://nc99-discovery:8080

spring:
  # Database Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://nc99-auth-database:3306/nc99_auth
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  # Storage COnfig
  web:
    resources:
      static-locations: ["file:/app/data"]
  mvc:
    static-path-pattern: "/storage/**"
storage:
  rootPath: "/app/data"

# Logging Config
logging:
  config: "classpath:configs/logback-prod.xml"
